language: java
sudo: required
group: edge

before_install:
  - sudo rm -f /etc/apt/sources.list.d/partner.list
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - sudo apt-get update -y
  - sudo apt-get install -y software-properties-common debconf-utils curl unzip
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -y
  - sudo apt-get install -y libstdc++6-4.7-dev
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update -y
  - echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
  - sudo apt-get install -y oracle-java8-installer
  - DEBIAN_FRONTEND="noninteractive" sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade -y --force-yes
  - DEBIAN_FRONTEND="noninteractive" sudo apt-get install -y oracle-java8-set-default
  - java -version
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add -
  - sudo apt-get update -y && sudo apt-get install -y bazel
  - sudo apt-get upgrade -y bazel
script:
  - export JDK_HOME=/usr/lib/jvm/java-8-oracle; export JAVA_HOME=/usr/lib/jvm/java-8-oracle; script/integration-test